name = "nostr-relay"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[vars]
# TODO: Override ENVIRONMENT in staging and production
ENVIRONMENT = "dev"

[durable_objects]
bindings = [
    { name = "NOSTR_RELAY", class_name = "NostrRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["NostrRelay"]
