name = "nostr-relay"
account_id = "9f1eb0ced2261c042002a14a7820d113"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[env.staging]
name = "nostr-relay-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.staging.durable_objects]
bindings = [
    { name = "NOSTR_RELAY", class_name = "NostrRelay" }
]

[env.prod]
name = "nostr-relay"

[env.prod.vars]
ENVIRONMENT = "production"

[env.prod.durable_objects]
bindings = [
    { name = "NOSTR_RELAY", class_name = "NostrRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["NostrRelay"]
