name = "nostr-relay"
main = "src/index.ts"
compatibility_date = "2023-09-18"

[durable_objects]
bindings = [
    { name = "NOSTR_RELAY", class_name = "NostrRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["NostrRelay"]
